### ISSUE TITLE
sparsnas_mqtt.yaml

### ISSUE THREAD

**Issue by berne88** [strigeus/sparsnas_decoder#12]
When using the code in sparsnas_mqtt.yaml i am getting error in HA

Invalid config for [sensor.mqtt]: [hidden] is an invalid option for [sensor.mqtt]. Check: sensor.mqtt->hidden. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/mqtt/
Invalid config for [sensor.mqtt]: [hidden] is an invalid option for [sensor.mqtt]. Check: sensor.mqtt->hidden. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/mqtt/
Invalid config for [sensor.mqtt]: [hidden] is an invalid option for [sensor.mqtt]. Check: sensor.mqtt->hidden. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/mqtt/
Invalid config for [sensor.mqtt]: [hidden] is an invalid option for [sensor.mqtt]. Check: sensor.mqtt->hidden. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/mqtt/
Invalid config for [sensor.mqtt]: [hidden] is an invalid option for [sensor.mqtt]. Check: sensor.mqtt->hidden. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/mqtt/

and this 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 248, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 220, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for -: 'float' and 'str'

hope this get an update its a great one love it

**Comment by Certekz** [comment]
Did you resolve this issue?
